p8105_hw2_cl4946.Rmd
================
Chen Li
2026-10-07

\#Problem 1 \### To import data and clean names

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
Subway_df = 
  read.csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")

Subway_df = 
  janitor::clean_names(Subway_df)
```

### Then read and clean the data; retain line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance.

``` r
Subway_df =
  Subway_df |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
dim(Subway_df)
```

    ## [1] 1868   19

Now this dataset contains subway line and station name, station
latitude/ longitude, routes served, entry status, vending availability,
entrance type, and ADA. I cleaned the variable names using
janitor::clean_names(), selected the variables relevant to this
analysis, and converted the entry variable from “YES” and “NO” character
values to a logical variable. The resulting dataset has 1868 rows and 19
columns. The data are not fully tidy because route information is spread
across route1 to route11 instead of being stored in one variable.

``` r
###How many distinct stations?
Subway_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

``` r
###How many stations are ADA compliant?

Subway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

``` r
###What proportion of station entrances / exits without vending allow entrance?
Subway_df |>
  filter(vending == "NO") |>
  summarize(
    proportion = mean(entry)
  )
```

    ##   proportion
    ## 1  0.3770492

``` r
### How many distinct stations serve the A train? and how many are ADA compliant?
Subway_long =
  Subway_df |>
  mutate(
    across(route1:route11, as.character)
  ) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name"
  )

Subway_long |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

``` r
Subway_long |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 17

# Question 2

### specify the sheet in the Excel file and to omit non-data entries (rows with notes / figures; columns containing notes) using arguments in read_excel

``` r
trash_df = 
  readxl::read_excel("./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N549"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    sports_balls = as.integer(round(sports_balls))
  )
```

### To combine data from from Mr. Trash Wheel, Professor Trash Wheel , and Gwynnda

``` r
trash_path = "data/202610 Trash Wheel Collection Data.xlsx"

# Mr. Trash Wheel
mr_trash_df =
  readxl::read_excel(
    trash_path,
    sheet = "Mr. Trash Wheel",
    range = readxl::cell_limits(
      c(2, 1),
      c(NA, 14)
    ),
    na = c("", "NA", "dive")
  ) |>
  janitor::clean_names() |>
  tidyr::drop_na(dumpster) |>
  dplyr::mutate(
    dumpster = as.integer(dumpster),
    month = stringr::str_to_title(
      stringr::str_trim(month)
    ),
    year = as.integer(year),
    sports_balls =
      as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )


# Professor Trash Wheel
professor_trash_df =
  readxl::read_excel(
    trash_path,
    sheet = "Professor Trash Wheel",
    range = readxl::cell_limits(
      c(2, 1),
      c(NA, 13)
    ),
    na = c("", "NA", "dive")
  ) |>
  janitor::clean_names() |>
  tidyr::drop_na(dumpster) |>
  dplyr::mutate(
    dumpster = as.integer(dumpster),
    month = stringr::str_to_title(
      stringr::str_trim(month)
    ),
    year = as.integer(year),
    trash_wheel = "Professor Trash Wheel"
  )


# Gwynnda
gwynnda_df =
  readxl::read_excel(
    trash_path,
    sheet = "Gwynnda the Good Wheel of the W",
    range = readxl::cell_limits(
      c(2, 1),
      c(NA, 12)
    ),
    na = c("", "NA", "dive")
  ) |>
  janitor::clean_names() |>
  tidyr::drop_na(dumpster) |>
  dplyr::mutate(
    dumpster = as.integer(dumpster),
    month = stringr::str_to_title(
      stringr::str_trim(month)
    ),
    year = as.integer(year),
    trash_wheel = "Gwynnda"
  )

trash_df =
  dplyr::bind_rows(
    mr_trash_df,
    professor_trash_df,
    gwynnda_df
  ) |>
  dplyr::select(
    trash_wheel,
    everything()
  )

dim(trash_df)
```

    ## [1] 1269   15

``` r
names(trash_df)
```

    ##  [1] "trash_wheel"        "dumpster"           "month"             
    ##  [4] "year"               "date"               "weight_tons"       
    ##  [7] "volume_cubic_yards" "plastic_bottles"    "polystyrene"       
    ## [10] "cigarette_butts"    "glass_bottles"      "plastic_bags"      
    ## [13] "wrappers"           "sports_balls"       "homes_powered"

After cleaning and combining the three Trash Wheel datasets, the
resulting dataset contains 1269 observations and 15 variables. Key
variables include `trash_wheel`, `dumpster`, `month`, `year`,
`weight_tons`, `plastic_bottles`, and `cigarette_butts`. Based on the
available data, Professor Trash Wheel collected a total of 294.96 tons
of trash. In June 2022, Gwynnda collected a total of 18,120 cigarette
butts.
